"""
database.py — SQLAlchemy models for the Autonomous Hiring System.
Stores candidates, interactions, scores, anti-cheat flags, and system learnings.
"""

from sqlalchemy import (
    create_engine, Column, Integer, String, Float,
    DateTime, Text, JSON, Boolean, ForeignKey
)
from sqlalchemy.orm import declarative_base, sessionmaker, relationship
from datetime import datetime
import os

Base = declarative_base()

# ── Models 

class Candidate(Base):
    """One row per applicant extracted from the job platform."""
    __tablename__ = "candidates"

    id            = Column(Integer, primary_key=True)
    name          = Column(String(200))
    email         = Column(String(200), unique=True, index=True)
    phone         = Column(String(50))
    college       = Column(String(300))
    github_url    = Column(String(500))
    resume_url    = Column(String(500))
    skills        = Column(Text)              # comma-separated
    answers       = Column(JSON)             # dict: question → answer
    raw_data      = Column(JSON)             # original scraped payload

    # Scoring
    total_score   = Column(Float, default=0.0)
    score_breakdown = Column(JSON)           # component scores
    tier          = Column(String(50))       # Fast-Track / Standard / Review / Reject

    # Anti-cheat
    ai_flag_count  = Column(Integer, default=0)
    copy_flag_count = Column(Integer, default=0)
    timing_flag_count = Column(Integer, default=0)
    total_strikes  = Column(Integer, default=0)
    is_eliminated  = Column(Boolean, default=False)

    # Engagement state
    current_round  = Column(Integer, default=0)
    last_email_sent_at = Column(DateTime)
    last_reply_at  = Column(DateTime)

    created_at    = Column(DateTime, default=datetime.utcnow)
    updated_at    = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    interactions  = relationship("Interaction", back_populates="candidate")
    anti_cheat_logs = relationship("AntiCheatLog", back_populates="candidate")
    review_notes  = relationship("ReviewNote", back_populates="candidate")


class Interaction(Base):
    """Every email sent or received for a candidate."""
    __tablename__ = "interactions"

    id           = Column(Integer, primary_key=True)
    candidate_id = Column(Integer, ForeignKey("candidates.id"), index=True)
    direction    = Column(String(10))  # 'sent' | 'received'
    subject      = Column(String(500))
    body         = Column(Text)
    thread_id    = Column(String(200))  # Gmail thread ID
    message_id   = Column(String(200))
    round_number = Column(Integer)
    timestamp    = Column(DateTime, default=datetime.utcnow)
    reply_latency_seconds = Column(Integer)  # seconds from our email to their reply

    candidate    = relationship("Candidate", back_populates="interactions")


class AntiCheatLog(Base):
    """Each detection event that contributed a strike."""
    __tablename__ = "anti_cheat_logs"

    id           = Column(Integer, primary_key=True)
    candidate_id = Column(Integer, ForeignKey("candidates.id"), index=True)
    check_type   = Column(String(50))   # 'ai_generated' | 'copy_ring' | 'timing'
    similarity_score = Column(Float)
    details      = Column(Text)
    timestamp    = Column(DateTime, default=datetime.utcnow)

    candidate    = relationship("Candidate", back_populates="anti_cheat_logs")


class ReviewNote(Base):
    """Internal recruiter-facing review notes that should not count as strikes."""
    __tablename__ = "review_notes"

    id           = Column(Integer, primary_key=True)
    candidate_id = Column(Integer, ForeignKey("candidates.id"), index=True)
    review_type  = Column(String(50))   # 'AI_REVIEW' | 'CODE_REVIEW'
    score        = Column(Float, default=0.0)
    summary      = Column(Text)
    created_at   = Column(DateTime, default=datetime.utcnow)

    candidate    = relationship("Candidate", back_populates="review_notes")


class SystemLearning(Base):
    """Periodic insights generated by the Self-Learning agent."""
    __tablename__ = "system_learnings"

    id           = Column(Integer, primary_key=True)
    generated_at = Column(DateTime, default=datetime.utcnow)
    candidate_count = Column(Integer)   # how many candidates existed at analysis time
    insights     = Column(JSON)         # list of insight strings
    pattern_updates = Column(JSON)      # scoring weight adjustments suggested
    raw_report   = Column(Text)


class ScoringWeight(Base):
    """Dynamic scoring weights — updated by self-learning."""
    __tablename__ = "scoring_weights"

    id           = Column(Integer, primary_key=True)
    component    = Column(String(100), unique=True)  # e.g. 'github_quality'
    weight       = Column(Float)
    updated_at   = Column(DateTime, default=datetime.utcnow)


# ── Engine & Session factory 

def get_engine(db_url: str = None):
    url = db_url or os.getenv("DATABASE_URL", "sqlite:///hiring_system.db")
    return create_engine(url, echo=False)


def init_db(engine=None):
    """Create all tables if they don't exist and seed default scoring weights."""
    if engine is None:
        engine = get_engine()
    Base.metadata.create_all(engine)
    Session = sessionmaker(bind=engine)
    session = Session()

    # Seed default weights only on first run
    defaults = {
        "technical_skills": 0.25,
        "answer_quality":   0.25,
        "github_quality":   0.20,
        "ai_penalty":       0.15,
        "completeness":     0.15,
    }
    for comp, w in defaults.items():
        if not session.query(ScoringWeight).filter_by(component=comp).first():
            session.add(ScoringWeight(component=comp, weight=w))
    session.commit()
    session.close()
    return engine


def get_session(engine=None):
    if engine is None:
        engine = get_engine()
    return sessionmaker(bind=engine)()


def get_scoring_weights(session) -> dict[str, float]:
    """Return dynamic scoring weights, falling back to defaults when needed."""
    defaults = {
        "technical_skills": 0.25,
        "answer_quality": 0.25,
        "github_quality": 0.20,
        "ai_penalty": 0.15,
        "completeness": 0.15,
    }
    rows = session.query(ScoringWeight).all()
    if not rows:
        return defaults.copy()

    weights = defaults.copy()
    for row in rows:
        if row.component in weights and row.weight is not None:
            weights[row.component] = float(row.weight)
    return weights


def save_scoring_weights(session, weights: dict[str, float]) -> dict[str, float]:
    """
    Persist normalized scoring weights.
    Unknown keys are ignored so learning output can contain extra metadata safely.
    """
    allowed = {
        "technical_skills",
        "answer_quality",
        "github_quality",
        "ai_penalty",
        "completeness",
    }
    cleaned = {k: float(v) for k, v in weights.items() if k in allowed}
    for component, weight in cleaned.items():
        row = session.query(ScoringWeight).filter_by(component=component).first()
        if row:
            row.weight = weight
            row.updated_at = datetime.utcnow()
        else:
            session.add(ScoringWeight(component=component, weight=weight))
    return cleaned
